### PR TITLE
Redhat distro family support for PHP version switch

### PR DESCRIPTION
**Pull request by mhitza**
For the test, I've used the poorly documented `molecule side-effect` feature. It gets called by `molecule test` after the idempotency step.

Would you like me to wrap this specific change within a `block`, as it is the case with the dnf module-specific code in `setup-RedHat.yml`?

Since I'm referencing that block section which is enabled for versions of RedHat >=8, I might add changes for the default docker image to be cento8 (instead of centos7) and change the role meta information to state explicitly that it works with EL version 8 or higher?

Because there is no support for CentOS 7, the side-effect test will fail. Would you like me to remove centos7 from the Travis test matrix, or add a conditional for RedHat >=8 in the assertion block?

### CODE REVIEW

**Comment by MacFlurry** [comment]
Hello @mhitza ,

is your PR resolve this issue https://github.com/geerlingguy/ansible-role-php-versions/issues/52 ?

Thanks

**Comment by mhitza** [comment]
@MacFlurry indeed, that's the issue it's fixing.

**Comment by MacFlurry** [comment]
thanks a lot @mhitza , I hope @geerlingguy will merge it quickly :-)

**Comment by geerlingguy** [comment]
@mhitza - I'd leave the centos/rhel 8 specific dnf changes in a block, and I'd accept it at that point. I'm okay with not having everything work in 7/6 since this is new functionality.

**Comment by mhitza** [comment]
@geerlingguy not sure if there is anything you'd want me to change in this PR.

**Pull request closed without merging**
